# Generated by Django 4.2.7 on 2026-01-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
                ('summary_stats', models.JSONField()),
                ('equipment_distribution', models.JSONField()),
            ],
        ),
    ]
